Repository MJU-Capstone-6/DevMark-Android, pull requests merged in 2024-06, with the labels that each got.

#66 [MARK-117] RegistrationToken 로그인 시 전달
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/bookmark/BookmarkDetailMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/model/bookmark/BookmarkDTO.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/model/user/RequestLoginDTO.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/UserService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/UserRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/bookmark/BookmarkDetailEntity.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/repository/UserRepository.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/SignIn/SignInViewModel.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/bookmark/BookmarkFragment.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/splash/SplashActivity.kt
Labels: Type: Enhencement

#67 추천 포스트 목록 조회 & 상위 카테고리 목록 조회
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/workspace/RecommendPostMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/workspace/TopCategoryMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/model/workspace/ResponseRecommendPostDTO.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/model/workspace/ResponseTopCategoryDTO.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/WorkSpaceService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/WorkSpaceRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/TopCategory.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/RealRecommendPost.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/RecommendLink.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/RecommendPostItem.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/RecommendPosts.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/TopCategory.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/repository/WorkSpaceRepository.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/Recommend/RecommendFragment.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/RecommendFragment.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/RecommendRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/RecommendViewModel.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/TopCategoryLvAdapter.kt
Labels: Type: Enhencement

#68 [MARK-000] 워크스페이스 나가기 기능
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/WorkSpaceService.kt
Labels: Type: Enhencement

#70 [MARK-120] 리마인드 알림 목록 조회
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/user/NotificationMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/workspace/RecommendPostMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/workspace/TopCategoryMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/model/user/ResponseNotificationDTO.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/UserService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/UserRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/user/NotificationEntity.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/repository/UserRepository.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/utils/TimeUtil.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/Remind/RemindFragment.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/Remind/RemindRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/RecommendViewModel.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/remind/RemindViewModel.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace/WorkSpaceRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace/WorkspaceFragment.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace_select/SelectWorkspaceFragment.kt
  DevMark/app/src/main/res/layout/fragment_workspace.xml
  DevMark/app/src/main/res/layout/item_filter_list.xml
  DevMark/app/src/main/res/layout/item_remind_bookmark.xml
Labels: Type: Enhencement, Type: Modify

#71 [Chore] Clean Up
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/bookmark/CommentMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/bookmark/UpdateBookmarkMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/workspace/TopCategoryMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/mapper/workspace/WorkSpaceInfoMapper.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/KakaoAuthService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/NullOnEmptyConverterFactory.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/RetrofitClient.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/CommentService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/UserService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/remote/api/WorkSpaceService.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/BookmarkRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/CommentRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/UserPreferencesRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/UserRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/repository/WorkSpaceRepositoryImpl.kt
  DevMark/app/src/main/java/com/devmark/devmark/data/utils/PrettyJsonLogger.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/Member.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/Recommend.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/Remind.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/bookmark/RequestBookmarkEntity.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/comment/CommentEntity.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/TopCategory.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/model/workspace/WorkSpaceInfoEntity.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/repository/BookmarkRepository.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/repository/CommentRepository.kt
  DevMark/app/src/main/java/com/devmark/devmark/domain/repository/WorkSpaceRepository.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/custom/CustomDialog.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/utils/PermissionManager.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/utils/StingExtension.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/Setting/SignOutDialog.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/SignIn/SignInActivity.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/SignIn/SignInViewModel.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/RecommendRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/recommend/TopCategoryLvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/splash/SplashActivity.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/splash/SplashViewModel.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace/CategoryRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace/MemberRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace/WorkSpaceRvAdapter.kt
  DevMark/app/src/main/java/com/devmark/devmark/presentation/view/workspace_setting/WorkspaceSettingFragment.kt
  DevMark/app/src/main/res/layout/fragment_recommend.xml
  DevMark/app/src/main/res/layout/item_bookmark.xml
  DevMark/app/src/main/res/layout/item_workspace.xml
  DevMark/app/src/main/res/values/font_style.xml
Labels: Type: Modify
